angular.module('proyectosApp',[
  'ngRoute',
  'angularCSS',
  'ngTagsInput',
  'ngAnimate',
  'textAngular',
  'ui.bootstrap',
  'ngTouch',
  'presentacionProyectos',
  'listaProyectos',
  'nuevoProyecto'
])
