angular.module('sandboxApp', [
  'ngRoute',
  'angularCSS',
  'ngTagsInput',
  'ngAnimate',
  'angular.backtop',
  'ngFileUpload',
  'ejerciciosLista',
  'ejercicioDetalle',
  'profesorElegir',
  'profesorEjercicios',
  'misEjercicios',
  'nuevoEjercicio',
  'editarEjercicio',
])
